baseURL: http://redlinedoc.com
disablePathToLower: true
languageCode: en-us
title: Redline Doc
theme: hugo-octopress
permalinks:
  post: "/:year/:month/:day/:title/"
indexes:
  tag: tags
  category: categories

params:
  # If false, all of the post will appear on front page (and in pagination)
  truncate: true

  # Author's name (this will appear in metadata and under posts)
  author: "RedlineDoc"

  # This text appears in the site header under website title
  subtitle: ""

  # Used in the search engine
  searchEngineURL: "https://www.google.com/search"

  # Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so we will add it to index.html manually
  continueReadingText: "Would you like to know more?"

  # Google analytics code
  googleAnalytics: 

  # Disqus shortcode
  # Disable comments for a specific post by adding "comments: false" in its frontmatter
  disqusShortname: redlinedoc

  rss: true  # switch to true to enable RSS icon link

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the `rss` setting
  textrss: false

  # Website's default description
  defaultDescription: 

  # Populate this with your own search keywords - these will appear in the meta tags
  # defaultKeywords: ["keyword1" , "keyword2" , "keyword3" , "keyword4"]
...
